### ISSUE TITLE
Ped

### ISSUE THREAD

**Issue by erayko-dev** [NaorNC/nc-rental#1]
Hey, so I installed the script (very well built no issues) but there is no ped at the location, I can "third-eye" to see the option/menu, I can also rent the car and I get the contract and everything but there is  no ped. Would you be able to help me? 
![image](https://user-images.githubusercontent.com/76734458/157775783-964c3de5-a09a-423e-80d6-b309b71b1b9d.png)

**Comment by NaorNC** [comment]
In the next update I will make a ped built into the script.
Unfortunately I didn’t do this because I have a peds script separate from the script.
